import type { Story } from "./types";

// Public-domain sample audio so the player works with zero setup in demo mode.
// In live mode these are replaced by narrator uploads in Supabase Storage.
const SAMPLE = [
  "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
  "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3",
  "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
  "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-9.mp3",
  "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-12.mp3",
];

const donePipeline = [
  { stage: "uploaded", state: "done", detail: "Audio stored" },
  { stage: "transcribed", state: "done", detail: "ElevenLabs Scribe" },
  { stage: "moderated", state: "done", detail: "Claude Haiku" },
  { stage: "tagged", state: "done", detail: "Claude Sonnet" },
  { stage: "embedded", state: "done", detail: "pgvector" },
  { stage: "published", state: "done" },
] as Story["stages"];

const ctaJoin = { label: "Add your voice", href: "/share" };
const ctaDonate = { label: "Support NYIC's work", href: "#donate" };
const ctaAdvocate = { label: "Take action with us", href: "#advocate" };

export const SEED_STORIES: Story[] = [
  {
    id: "st_amina",
    memberOrg: "Arab American Association of New York",
    track: "new",
    narratorDisplay: "Amina",
    interviewerName: "Layla (her daughter)",
    location: "Astoria, Queens",
    origin: "Yemen",
    yearsInNY: 16,
    status: "published",
    stages: donePipeline,
    audioUrl: SAMPLE[0],
    durationSec: 287,
    language: "Arabic + English",
    transcript:
      "When we first came, I did not choose New York because I loved it. I chose it because my brother was here, and it was the only door that opened. The first winter, I cried at the bus stop because I could not read the signs. A woman — a stranger — she saw me and she walked me to my stop every morning for a week. She never asked what I did for work, what papers I had. She just chose to see me. That is when I understood: I belong here not because of what I give this city. I belong because someone chose me first. Now I do that for the new mothers at the mosque. I walk them to their stop.",
    summary:
      "A Yemeni mother on being 'chosen' by a stranger in her first NY winter — and paying it forward.",
    pullQuote: "I belong because someone chose me first.",
    tags: [
      { label: "Belonging", category: "theme" },
      { label: "Motherhood", category: "theme" },
      { label: "Hopeful", category: "emotion" },
      { label: "Community", category: "topic" },
      { label: "Middle age", category: "lifeStage" },
    ],
    sentiment: "hopeful",
    moderation: { flagged: false, sensitive: false },
    consent: {
      publicShare: true,
      identity: "name",
      displayName: "Amina",
      anonymizeVoice: false,
      allowCampaignUse: true,
    },
    featured: true,
    animationStatus: "rendered",
    nominations: 2,
    createdAt: "2026-03-21T14:02:00Z",
    cta: ctaJoin,
  },
  {
    id: "st_diego",
    memberOrg: "Make the Road New York",
    track: "new",
    narratorDisplay: "Diego",
    interviewerName: "Marcus (coworker)",
    location: "Sunset Park, Brooklyn",
    origin: "Mexico",
    yearsInNY: 9,
    status: "published",
    stages: donePipeline,
    audioUrl: SAMPLE[1],
    durationSec: 254,
    language: "Spanish",
    transcript:
      "Everybody asks me how many hours I work, like that's the whole story. Sí, I work. But the day I felt like a New Yorker was not a work day. It was the blackout. The power went down and my whole block came outside. We grilled everything in our freezers before it spoiled. Somebody brought a speaker. The kids played in the fire-hydrant water. Nobody asked where anybody was from. For one night we were just neighbors on Forty-Fourth Street. I want my son to know that belonging is not a paycheck. It's a block party in the dark.",
    summary:
      "A Brooklyn dad redefines belonging through a neighborhood blackout, not his work hours.",
    pullQuote: "Belonging is not a paycheck. It's a block party in the dark.",
    tags: [
      { label: "Belonging", category: "theme" },
      { label: "Community", category: "topic" },
      { label: "Family", category: "theme" },
      { label: "Uplifting", category: "emotion" },
      { label: "Fatherhood", category: "theme" },
    ],
    sentiment: "uplifting",
    moderation: { flagged: false, sensitive: false },
    consent: {
      publicShare: true,
      identity: "name",
      displayName: "Diego",
      anonymizeVoice: false,
      allowCampaignUse: true,
    },
    featured: true,
    animationStatus: "queued",
    nominations: 3,
    createdAt: "2026-05-24T18:30:00Z",
    cta: ctaAdvocate,
  },
  {
    id: "st_mei",
    memberOrg: "Chinese-American Planning Council",
    track: "legacy",
    narratorDisplay: "Mrs. Chen",
    interviewerName: "Grace (NYIC volunteer)",
    location: "Chinatown, Manhattan",
    origin: "China",
    yearsInNY: 38,
    status: "published",
    stages: donePipeline,
    audioUrl: SAMPLE[2],
    durationSec: 296,
    language: "Cantonese",
    transcript:
      "I came the same year this Coalition started — 1987. Back then we went to NYIC for help with papers, for English class, for a doctor who spoke our language. I remember a young organizer who sat with me for three hours to fill one form. Forty years later my granddaughter interns there. The help became the help-givers. People think immigrants only take. We built the scaffolding other people climb. But even on the days I built nothing, I was still a person who deserved a warm room and a kind voice. Remember that part too.",
    summary:
      "A 38-year Chinatown resident traces NYIC from her first ESL class to her granddaughter's internship.",
    pullQuote: "The help became the help-givers.",
    tags: [
      { label: "40-year history", category: "theme" },
      { label: "Legacy", category: "theme" },
      { label: "Bittersweet", category: "emotion" },
      { label: "Elder", category: "lifeStage" },
      { label: "Education", category: "topic" },
    ],
    sentiment: "bittersweet",
    moderation: { flagged: false, sensitive: false },
    consent: {
      publicShare: true,
      identity: "pseudonym",
      displayName: "Mrs. Chen",
      anonymizeVoice: false,
      allowCampaignUse: true,
    },
    featured: false,
    animationStatus: "none",
    nominations: 1,
    createdAt: "2026-02-12T16:45:00Z",
    cta: ctaDonate,
  },
  {
    id: "st_anon",
    memberOrg: "UnLocal",
    track: "new",
    narratorDisplay: "Anonymous",
    interviewerName: "A friend",
    location: "The Bronx",
    origin: "Withheld for safety",
    status: "in_review",
    stages: [
      { stage: "uploaded", state: "done", detail: "Audio stored" },
      { stage: "transcribed", state: "done", detail: "ElevenLabs Scribe" },
      {
        stage: "moderated",
        state: "flagged",
        detail: "Sensitive: detention experience",
      },
      { stage: "tagged", state: "pending" },
      { stage: "embedded", state: "pending" },
      { stage: "published", state: "pending" },
    ],
    audioUrl: SAMPLE[3],
    durationSec: 241,
    language: "Spanish",
    transcript:
      "I don't want my face anywhere. I was in detention for four months and I still wake up at the same time the guards used to count us. But I want people to hear this: in there, an officer from NYIC's hotline kept calling to check I was alive. One phone call a week. That call was the only thing that told me I still existed to somebody outside. If you are listening and you feel invisible — somebody is choosing you right now. I promise.",
    summary:
      "An anonymous narrator on a weekly NYIC hotline call that anchored them through detention.",
    pullQuote: "That call was the only thing that told me I still existed.",
    tags: [
      { label: "Detention", category: "topic" },
      { label: "Resilience", category: "theme" },
      { label: "Somber", category: "emotion" },
    ],
    sentiment: "somber",
    moderation: {
      flagged: true,
      reason:
        "Describes immigration detention. Not policy-violating — handle with care, confirm consent, offer support resources.",
      sensitive: true,
    },
    consent: {
      publicShare: true,
      identity: "anonymous",
      displayName: "Anonymous",
      anonymizeVoice: true,
      allowCampaignUse: false,
    },
    featured: false,
    animationStatus: "none",
    nominations: 0,
    createdAt: "2026-05-29T09:15:00Z",
    cta: ctaAdvocate,
  },
  {
    id: "st_fatou",
    memberOrg: "African Communities Together",
    track: "new",
    narratorDisplay: "Fatou",
    interviewerName: "Aisha (best friend)",
    location: "Harlem, Manhattan",
    origin: "Senegal",
    yearsInNY: 4,
    status: "published",
    stages: donePipeline,
    audioUrl: SAMPLE[4],
    durationSec: 233,
    language: "French + Wolof",
    transcript:
      "My braiding shop is small, two chairs. But you should hear the conversations in those chairs. A woman from Honduras and a woman from Senegal arguing about whose grandmother's rice is better, in two languages, laughing. I think that is New York. Not the buildings. The chairs where strangers become aunties. People tell me, Fatou, you contribute so much to the economy. Okay. But I was a whole person before I braided a single head of hair. My worth did not start at the cash register.",
    summary:
      "A Harlem braider on her two-chair shop as a tiny embassy of belonging.",
    pullQuote: "My worth did not start at the cash register.",
    tags: [
      { label: "Belonging", category: "theme" },
      { label: "Community", category: "topic" },
      { label: "Uplifting", category: "emotion" },
      { label: "Young adult", category: "lifeStage" },
      { label: "Women", category: "theme" },
    ],
    sentiment: "uplifting",
    moderation: { flagged: false, sensitive: false },
    consent: {
      publicShare: true,
      identity: "name",
      displayName: "Fatou",
      anonymizeVoice: false,
      allowCampaignUse: true,
    },
    featured: false,
    animationStatus: "none",
    nominations: 2,
    createdAt: "2026-04-27T20:10:00Z",
    cta: ctaJoin,
  },
  {
    id: "st_emeka",
    memberOrg: "African Communities Together",
    track: "legacy",
    narratorDisplay: "Mr. Okonkwo",
    interviewerName: "David (NYIC volunteer)",
    location: "East Flatbush, Brooklyn",
    origin: "Nigeria",
    yearsInNY: 31,
    status: "published",
    stages: donePipeline,
    audioUrl: SAMPLE[1],
    durationSec: 279,
    language: "Igbo + English",
    transcript:
      "In the nineties, nobody was writing our stories down. We organized in church basements, we filled out each other's forms, we taught the new ones English on Saturday mornings. NYIC was the thread that tied the basements together. I drove a cab thirty-one years. People reduce a man to his work. But on Saturday mornings I was a teacher. That is the part history forgets. I am glad somebody is finally pressing record — so the next forty years know we were here, and that we taught each other to belong.",
    summary:
      "A Nigerian elder on teaching English in church basements and the 1990s organizing NYIC tied together.",
    pullQuote: "On Saturday mornings I was a teacher. History forgets that part.",
    tags: [
      { label: "40-year history", category: "theme" },
      { label: "Legacy", category: "theme" },
      { label: "Education", category: "topic" },
      { label: "Bittersweet", category: "emotion" },
      { label: "Elder", category: "lifeStage" },
    ],
    sentiment: "bittersweet",
    moderation: { flagged: false, sensitive: false },
    consent: {
      publicShare: true,
      identity: "name",
      displayName: "Mr. Okonkwo",
      anonymizeVoice: false,
      allowCampaignUse: true,
    },
    featured: false,
    animationStatus: "none",
    nominations: 1,
    createdAt: "2026-01-18T15:20:00Z",
    cta: ctaDonate,
  },
  {
    id: "st_rosa",
    memberOrg: "Mixteca Organization",
    track: "new",
    narratorDisplay: "Rosa",
    interviewerName: "Camila (her niece)",
    location: "Grand Concourse, The Bronx",
    origin: "Dominican Republic",
    yearsInNY: 22,
    status: "published",
    stages: donePipeline,
    audioUrl: SAMPLE[2],
    durationSec: 248,
    language: "Spanish",
    transcript:
      "On my block in the Bronx, everybody knows my door is the one with food behind it. I feed whoever shows up — the kids whose parents work nights, the viejito on the corner. People say, Rosa, you should rest. But feeding people is how my mother taught me to pray. I did not come here to take anything. I came to set one more place at the table. That is what we Dominicans do. The table just keeps getting longer.",
    summary:
      "A Bronx grandmother on keeping an open door and a longer table for 22 years.",
    pullQuote: "I came to set one more place at the table.",
    tags: [
      { label: "Belonging", category: "theme" },
      { label: "Family", category: "theme" },
      { label: "Community", category: "topic" },
      { label: "Hopeful", category: "emotion" },
      { label: "Elder", category: "lifeStage" },
    ],
    sentiment: "hopeful",
    moderation: { flagged: false, sensitive: false },
    consent: {
      publicShare: true,
      identity: "name",
      displayName: "Rosa",
      anonymizeVoice: false,
      allowCampaignUse: true,
    },
    featured: false,
    animationStatus: "none",
    nominations: 2,
    createdAt: "2026-03-08T13:00:00Z",
    cta: ctaDonate,
  },
  {
    id: "st_joseph",
    memberOrg: "African Communities Together",
    track: "legacy",
    narratorDisplay: "Joseph",
    interviewerName: "Emmanuel (church friend)",
    location: "Park Hill, Staten Island",
    origin: "Liberia",
    yearsInNY: 27,
    status: "published",
    stages: donePipeline,
    audioUrl: SAMPLE[3],
    durationSec: 263,
    language: "English + Liberian Kreyol",
    transcript:
      "They call Park Hill 'Little Liberia.' When the war sent us here, we had nothing but each other and the church on Targee Street. NYIC helped us when nobody knew Staten Island had Africans. People forget there is a whole country on this island. I drove the S78 bus for twenty years. But I am not the bus. I am the man who kept a piece of Monrovia alive on a island most New Yorkers never visit.",
    summary:
      "A Liberian elder on keeping 'Little Liberia' alive on Staten Island for 27 years.",
    pullQuote: "I kept a piece of Monrovia alive on an island most New Yorkers never visit.",
    tags: [
      { label: "Legacy", category: "theme" },
      { label: "Community", category: "topic" },
      { label: "Resilience", category: "theme" },
      { label: "Bittersweet", category: "emotion" },
      { label: "Elder", category: "lifeStage" },
    ],
    sentiment: "bittersweet",
    moderation: { flagged: false, sensitive: false },
    consent: {
      publicShare: true,
      identity: "name",
      displayName: "Joseph",
      anonymizeVoice: false,
      allowCampaignUse: true,
    },
    featured: false,
    animationStatus: "none",
    nominations: 1,
    createdAt: "2026-02-25T11:30:00Z",
    cta: ctaAdvocate,
  },
  {
    id: "st_processing",
    memberOrg: "DRUM – Desis Rising Up & Moving",
    track: "new",
    narratorDisplay: "Processing…",
    interviewerName: "A friend",
    location: "Jackson Heights, Queens",
    origin: "Bangladesh",
    status: "processing",
    stages: [
      { stage: "uploaded", state: "done", detail: "Audio stored" },
      { stage: "transcribed", state: "running", detail: "ElevenLabs Scribe" },
      { stage: "moderated", state: "pending" },
      { stage: "tagged", state: "pending" },
      { stage: "embedded", state: "pending" },
      { stage: "published", state: "pending" },
    ],
    audioUrl: SAMPLE[0],
    durationSec: 268,
    language: "detecting…",
    transcript: "",
    summary: "",
    pullQuote: "",
    tags: [],
    sentiment: "hopeful",
    moderation: { flagged: false, sensitive: false },
    consent: {
      publicShare: true,
      identity: "name",
      displayName: "Rina",
      anonymizeVoice: false,
      allowCampaignUse: true,
    },
    featured: false,
    animationStatus: "none",
    nominations: 0,
    createdAt: "2026-05-31T05:20:00Z",
    cta: ctaJoin,
  },
];
